#!/usr/bin/env python3
# Copyright 2022 Robert Krawitz/Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Thin wrapper: analyze-clusterbuster-report CLI lives in ClusterBusterAnalysis.run_analysis.
# Code written by Cursor (Auto).

import sys
from lib.clusterbuster.reporting.analysis.ClusterBusterAnalysis import ClusterBusterAnalysis
from lib.clusterbuster.reporting.reporting_exceptions import ClusterBusterReportingException
import os

if 'CB_LIBPATH' in os.environ:
    sys.path = [element for element in os.environ['CB_LIBPATH'].split(':')] + sys.path

try:
    if not ClusterBusterAnalysis.run_analysis():
        sys.exit(1)
except (KeyboardInterrupt, BrokenPipeError):
    sys.exit(1)
except ClusterBusterReportingException as exc:
    print(f'Report failed: {str(exc)}')
    sys.exit(1)
