#!/usr/bin/env python3
"""Deep structural comparison of bash vs Python YAML output.

Compares every field of every Kubernetes object generated by both versions.
Designed as a one-time analysis tool, not a permanent test.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from typing import Any

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXED_UUID = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
BASH_CMD = os.path.join(REPO_ROOT, "clusterbuster.sh")

WORKLOADS = [
    "cpusoaker", "failure", "files", "fio", "hammerdb",
    "logger", "memory", "pausepod", "server", "sleep",
    "synctest", "sysbench", "uperf", "waitforever",
]
DEPLOYMENT_TYPES = ["pod", "vm", "deployment", "replicaset"]

_UUID_RE = re.compile(
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
    re.IGNORECASE,
)


def _normalize(val: Any) -> Any:
    """Recursively normalize UUIDs and timestamps in values."""
    if isinstance(val, str):
        val = val.replace(FIXED_UUID, "UUID")
        val = _UUID_RE.sub("XUUID", val)
        # Normalize timestamps like 1775863708.713340162
        val = re.sub(r"\d{10}\.\d+", "TIMESTAMP", val)
        # Normalize SSH keys
        val = re.sub(r"ssh-\S+ \S+", "SSH_KEY", val)
        return val
    if isinstance(val, dict):
        return {k: _normalize(v) for k, v in val.items()}
    if isinstance(val, list):
        return [_normalize(v) for v in val]
    return val


def _extract_yaml_documents(raw: str) -> list[dict]:
    """Parse multi-doc YAML, skipping non-YAML lines."""
    docs = []
    current_lines: list[str] = []
    in_doc = False
    for line in raw.splitlines():
        if line.strip() == "---":
            if in_doc and current_lines:
                text = "\n".join(current_lines)
                try:
                    doc = yaml.safe_load(text)
                    if isinstance(doc, dict) and "kind" in doc:
                        docs.append(doc)
                except Exception:
                    pass
                current_lines = []
            in_doc = True
            continue
        if not in_doc:
            continue
        if re.match(r"^\d{4}-\d{2}-\d{2}T", line):
            continue
        current_lines.append(line)
    if in_doc and current_lines:
        text = "\n".join(current_lines)
        try:
            doc = yaml.safe_load(text)
            if isinstance(doc, dict) and "kind" in doc:
                docs.append(doc)
        except Exception:
            pass
    return docs


def run_bash(workload: str, dep_type: str) -> list[dict] | None:
    args = ["bash", BASH_CMD, f"--uuid={FIXED_UUID}",
            f"--workload={workload}", f"--deployment-type={dep_type}", "-n"]
    try:
        result = subprocess.run(args, capture_output=True, text=True,
                                timeout=60, cwd=REPO_ROOT)
        if result.returncode != 0:
            return None
        return _extract_yaml_documents(result.stdout + result.stderr)
    except Exception:
        return None


def run_python(workload: str, dep_type: str) -> list[dict] | None:
    sys.path.insert(0, os.path.join(REPO_ROOT, "lib"))
    from io import StringIO
    old_stdout = sys.stdout
    sys.stdout = buf = StringIO()
    try:
        from clusterbuster.driver import run_from_argv
        rc = run_from_argv(["-n", f"--uuid={FIXED_UUID}",
                            f"--workload={workload}",
                            f"--deployment-type={dep_type}"])
        raw = buf.getvalue()
        if rc != 0:
            return None
        marker = "--- Manifests ---"
        idx = raw.find(marker)
        if idx >= 0:
            raw = raw[idx + len(marker):]
        docs = []
        for doc_text in raw.split("---"):
            doc_text = doc_text.strip()
            if not doc_text:
                continue
            try:
                doc = yaml.safe_load(doc_text)
                if isinstance(doc, dict) and "kind" in doc:
                    docs.append(doc)
            except Exception:
                pass
        return docs
    finally:
        sys.stdout = old_stdout
        # Reset workload singletons
        try:
            import copy
            from clusterbuster.driver.workload_registry import all_workloads
            for wl in all_workloads():
                pass
        except Exception:
            pass


def _obj_key(doc: dict) -> str:
    kind = doc.get("kind", "?")
    meta = doc.get("metadata", {})
    name = meta.get("name", "?")
    ns = meta.get("namespace", "")
    return f"{kind}/{ns}/{name}"


def _deep_diff(path: str, bash_val: Any, py_val: Any, diffs: list[str]) -> None:
    """Recursively compare two values and collect differences."""
    if type(bash_val) != type(py_val):
        # Allow int/float comparison
        if isinstance(bash_val, (int, float)) and isinstance(py_val, (int, float)):
            if bash_val != py_val:
                diffs.append(f"  {path}: bash={bash_val} vs python={py_val}")
            return
        diffs.append(f"  {path}: type mismatch bash={type(bash_val).__name__}({bash_val!r}) vs python={type(py_val).__name__}({py_val!r})")
        return

    if isinstance(bash_val, dict):
        all_keys = set(bash_val.keys()) | set(py_val.keys())
        for k in sorted(all_keys):
            if k not in bash_val:
                diffs.append(f"  {path}.{k}: MISSING in bash, python={_normalize(py_val[k])!r}")
            elif k not in py_val:
                diffs.append(f"  {path}.{k}: MISSING in python, bash={_normalize(bash_val[k])!r}")
            else:
                _deep_diff(f"{path}.{k}", bash_val[k], py_val[k], diffs)
    elif isinstance(bash_val, list):
        if len(bash_val) != len(py_val):
            diffs.append(f"  {path}: list length bash={len(bash_val)} vs python={len(py_val)}")
            # Still compare common elements
            for i in range(min(len(bash_val), len(py_val))):
                _deep_diff(f"{path}[{i}]", bash_val[i], py_val[i], diffs)
            for i in range(min(len(bash_val), len(py_val)), len(bash_val)):
                diffs.append(f"  {path}[{i}]: MISSING in python, bash={_normalize(bash_val[i])!r}")
            for i in range(min(len(bash_val), len(py_val)), len(py_val)):
                diffs.append(f"  {path}[{i}]: MISSING in bash, python={_normalize(py_val[i])!r}")
        else:
            for i in range(len(bash_val)):
                _deep_diff(f"{path}[{i}]", bash_val[i], py_val[i], diffs)
    else:
        # Normalize for comparison
        bash_n = _normalize(bash_val)
        py_n = _normalize(py_val)
        if bash_n != py_n:
            diffs.append(f"  {path}: bash={bash_n!r} vs python={py_n!r}")


def match_objects(bash_docs: list[dict], py_docs: list[dict]) -> list[tuple[dict | None, dict | None, str]]:
    """Match bash and python objects by kind + functional role."""
    pairs: list[tuple[dict | None, dict | None, str]] = []
    py_used: set[int] = set()

    for b_doc in bash_docs:
        b_kind = b_doc.get("kind", "")
        b_name = _normalize(b_doc.get("metadata", {}).get("name", ""))
        b_ns = _normalize(b_doc.get("metadata", {}).get("namespace", ""))
        b_labels = b_doc.get("metadata", {}).get("labels", {})
        b_objtype = b_labels.get("clusterbuster-objtype", "")

        best_idx = None
        best_score = -1
        for i, p_doc in enumerate(py_docs):
            if i in py_used:
                continue
            if p_doc.get("kind") != b_kind:
                continue
            p_name = _normalize(p_doc.get("metadata", {}).get("name", ""))
            p_ns = _normalize(p_doc.get("metadata", {}).get("namespace", ""))
            p_labels = p_doc.get("metadata", {}).get("labels", {})
            p_objtype = p_labels.get("clusterbuster-objtype", "")

            score = 0
            if p_name == b_name:
                score += 10
            if p_ns == b_ns:
                score += 5
            if p_objtype == b_objtype:
                score += 3
            if score > best_score:
                best_score = score
                best_idx = i

        if best_idx is not None:
            py_used.add(best_idx)
            pairs.append((b_doc, py_docs[best_idx], f"{b_kind}/{b_ns}/{b_name}"))
        else:
            pairs.append((b_doc, None, f"{b_kind}/{b_ns}/{b_name}"))

    for i, p_doc in enumerate(py_docs):
        if i not in py_used:
            p_kind = p_doc.get("kind", "")
            p_name = _normalize(p_doc.get("metadata", {}).get("name", ""))
            p_ns = _normalize(p_doc.get("metadata", {}).get("namespace", ""))
            pairs.append((None, p_doc, f"{p_kind}/{p_ns}/{p_name}"))

    return pairs


def compare_workload(workload: str, dep_type: str) -> dict:
    """Compare one workload × deployment type. Return summary."""
    bash_docs = run_bash(workload, dep_type)
    py_docs = run_python(workload, dep_type)

    if bash_docs is None:
        return {"status": "bash_failed"}
    if py_docs is None:
        return {"status": "python_failed"}

    # Filter out ConfigMap and Secret from both (Python-only kinds in golden tests)
    bash_filtered = [d for d in bash_docs if d.get("kind") not in ("ConfigMap", "Secret")]
    py_filtered = [d for d in py_docs if d.get("kind") not in ("ConfigMap", "Secret")]

    result: dict = {
        "status": "compared",
        "bash_objects": len(bash_filtered),
        "python_objects": len(py_filtered),
        "object_diffs": [],
    }

    pairs = match_objects(bash_filtered, py_filtered)
    for b_doc, p_doc, key in pairs:
        obj_result: dict = {"key": key}
        if b_doc is None:
            obj_result["issue"] = "python_only"
            result["object_diffs"].append(obj_result)
            continue
        if p_doc is None:
            obj_result["issue"] = "bash_only"
            result["object_diffs"].append(obj_result)
            continue

        diffs: list[str] = []
        _deep_diff("", b_doc, p_doc, diffs)
        if diffs:
            obj_result["diffs"] = diffs
            result["object_diffs"].append(obj_result)

    return result


def main() -> None:
    if len(sys.argv) > 1:
        # Allow filtering: deep_compare.py <workload> [dep_type]
        workloads = [sys.argv[1]]
        dep_types = [sys.argv[2]] if len(sys.argv) > 2 else DEPLOYMENT_TYPES
    else:
        workloads = WORKLOADS
        dep_types = DEPLOYMENT_TYPES

    all_diffs: dict[str, list[str]] = {}

    for wl in workloads:
        for dt in dep_types:
            key = f"{wl}/{dt}"
            print(f"Comparing {key}...", end=" ", flush=True)
            result = compare_workload(wl, dt)
            if result["status"] != "compared":
                print(f"SKIP ({result['status']})")
                continue

            obj_diffs = result["object_diffs"]
            if not obj_diffs:
                print("OK (no diffs)")
                continue

            diff_lines: list[str] = []
            for od in obj_diffs:
                if "issue" in od:
                    diff_lines.append(f"  [{od['key']}] {od['issue']}")
                elif "diffs" in od:
                    diff_lines.append(f"  [{od['key']}]")
                    diff_lines.extend(od["diffs"])

            all_diffs[key] = diff_lines
            total_field_diffs = sum(len(od.get("diffs", [])) for od in obj_diffs)
            print(f"DIFFS: {len(obj_diffs)} objects, {total_field_diffs} field differences")

    print("\n" + "=" * 80)
    print("DETAILED DIFFERENCES")
    print("=" * 80)
    for key, lines in sorted(all_diffs.items()):
        print(f"\n--- {key} ---")
        for line in lines:
            print(line)

    print(f"\n\nTotal workload/dep_type combos with diffs: {len(all_diffs)}")


if __name__ == "__main__":
    sys.exit(main() or 0)
