# Copyright 2026 Robert Krawitz/Red Hat
# Licensed under the Apache License, Version 2.0
"""Golden-file parity tests: compare clusterbuster (Python) against
clusterbuster.sh (bash) output for labels, objects, and services.

Golden files live in tests/golden/ and were generated by
tests/generate_golden.py from the bash version.  Regenerate with:
    python tests/generate_golden.py
"""

from __future__ import annotations

import copy
import json
import re
from pathlib import Path
from typing import Any

import pytest

FIXED_UUID = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
GOLDEN_DIR = Path(__file__).parent / "golden"

WORKLOADS = [
    "cpusoaker", "failure", "files", "fio", "hammerdb",
    "logger", "memory", "pausepod", "server", "sleep",
    "synctest", "sysbench", "uperf", "waitforever",
]

DEPLOYMENT_TYPES = ["pod", "vm", "deployment", "replicaset"]

_UUID_RE = re.compile(
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
    re.IGNORECASE,
)

PYTHON_ONLY_KINDS = frozenset({"ConfigMap", "Secret"})

# Object kinds that represent workload pods/VMs (not infra).
_WORKER_KINDS = frozenset({
    "Pod", "Deployment", "ReplicaSet", "VirtualMachine",
})

# Client-server workloads where the server role forces pods in bash.
_CLIENT_SERVER = frozenset({"server", "uperf"})


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _normalize_uuid(val: str) -> str:
    val = val.replace(FIXED_UUID, "UUID")
    return _UUID_RE.sub("XUUID", val)


def _extract_object_info(doc: dict[str, Any]) -> dict[str, Any]:
    """Extract structural info from a parsed k8s manifest."""
    meta = doc.get("metadata", {})
    kind = doc.get("kind", "")
    info: dict[str, Any] = {
        "kind": kind,
        "name": _normalize_uuid(str(meta.get("name", ""))),
        "namespace": _normalize_uuid(str(meta.get("namespace", ""))),
    }

    labels = meta.get("labels", {})
    if labels:
        info["labels"] = {
            k: _normalize_uuid(str(v)) for k, v in sorted(labels.items())
        }

    spec = doc.get("spec", {})
    if kind == "Service":
        ports = spec.get("ports", [])
        if ports:
            info["ports"] = [
                {
                    "port": p.get("port"),
                    "protocol": p.get("protocol", "TCP"),
                }
                for p in ports
            ]
        selector = spec.get("selector", {})
        if selector:
            info["selector"] = {
                k: _normalize_uuid(str(v)) for k, v in sorted(selector.items())
            }
        svc_type = spec.get("type", "")
        if svc_type:
            info["service_type"] = svc_type
        if spec.get("clusterIP") in ("None", None) and "clusterIP" in spec:
            info["headless"] = True

    if kind == "Pod":
        restart = spec.get("restartPolicy")
        if restart:
            info["restart_policy"] = restart
        containers = spec.get("containers", [])
        if containers:
            sc = containers[0].get("securityContext", {})
            if "runAsNonRoot" in sc:
                info["run_as_non_root"] = sc["runAsNonRoot"]
            if sc.get("sysctls"):
                info["container_sysctls"] = [
                    s["name"] for s in sc["sysctls"]
                ]
        if spec.get("affinity", {}).get("podAffinity"):
            info["has_pod_affinity"] = True

    if kind in ("Deployment", "ReplicaSet"):
        tmpl = spec.get("template", {}).get("metadata", {})
        tmpl_labels = tmpl.get("labels", {})
        if tmpl_labels:
            info["template_labels"] = {
                k: _normalize_uuid(str(v))
                for k, v in sorted(tmpl_labels.items())
            }
        sel = spec.get("selector", {}).get("matchLabels", {})
        if sel:
            info["match_labels"] = {
                k: _normalize_uuid(str(v)) for k, v in sorted(sel.items())
            }
        tmpl_spec = spec.get("template", {}).get("spec", {})
        restart = tmpl_spec.get("restartPolicy")
        if restart:
            info["restart_policy"] = restart
        containers = tmpl_spec.get("containers", [])
        if containers:
            sc = containers[0].get("securityContext", {})
            if "runAsNonRoot" in sc:
                info["run_as_non_root"] = sc["runAsNonRoot"]
            if sc.get("sysctls"):
                info["container_sysctls"] = [
                    s["name"] for s in sc["sysctls"]
                ]

    if kind == "VirtualMachine":
        tmpl = spec.get("template", {}).get("metadata", {})
        tmpl_labels = tmpl.get("labels", {})
        if tmpl_labels:
            info["template_labels"] = {
                k: _normalize_uuid(str(v))
                for k, v in sorted(tmpl_labels.items())
            }

        vm_spec = spec.get("template", {}).get("spec", {})
        domain = vm_spec.get("domain", {})
        devices = domain.get("devices", {})

        disks = devices.get("disks", [])
        serials = sorted(d["serial"] for d in disks if d.get("serial"))
        if serials:
            info["vm_disk_serials"] = serials

        volumes = vm_spec.get("volumes", [])
        vol_types = sorted(
            next((k for k in v if k != "name"), "unknown")
            for v in volumes
        )
        if vol_types:
            info["vm_volume_types"] = vol_types

        ci_vols = [v for v in volumes if "cloudInitNoCloud" in v]
        if ci_vols:
            import yaml
            userdata = ci_vols[0]["cloudInitNoCloud"].get("userData", "")
            try:
                ci_doc = yaml.safe_load(userdata)
                if isinstance(ci_doc, dict):
                    bootcmds = ci_doc.get("bootcmd", [])
                    structural = []
                    for cmd in bootcmds:
                        if not isinstance(cmd, str):
                            continue
                        verb = cmd.strip().split()[0].strip("'\"")
                        if verb in ("mkdir", "mount") or verb.startswith("mkfs"):
                            structural.append(verb)
                    if structural:
                        info["vm_bootcmd_structural"] = structural
            except Exception:
                pass

    return info


def _python_dryrun(workload: str, dep_type: str, capsys: Any) -> str:
    """Run Python clusterbuster dry-run and return stdout."""
    from clusterbuster.driver import run_from_argv
    args = [
        "-n",
        f"--uuid={FIXED_UUID}",
        f"--workload={workload}",
        f"--deployment-type={dep_type}",
    ]
    rc = run_from_argv(args)
    assert rc == 0, f"dry-run failed for {workload}/{dep_type}"
    return capsys.readouterr().out


def _extract_python_objects(raw: str) -> list[dict[str, Any]]:
    """Parse Python dry-run YAML output into extracted objects."""
    import yaml

    marker = "--- Manifests ---"
    idx = raw.find(marker)
    if idx >= 0:
        raw = raw[idx + len(marker):]

    objects: list[dict[str, Any]] = []
    for doc_text in raw.split("---"):
        doc_text = doc_text.strip()
        if not doc_text:
            continue
        try:
            doc = yaml.safe_load(doc_text)
        except Exception:
            continue
        if isinstance(doc, dict) and "kind" in doc:
            objects.append(_extract_object_info(doc))
    return objects


def _load_golden(workload: str, dep_type: str) -> list[dict[str, Any]]:
    path = GOLDEN_DIR / f"{workload}_{dep_type}.json"
    if not path.exists():
        pytest.skip(f"Golden file not found: {path.name}")
    return json.loads(path.read_text())


def _by_kind(objects: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    result: dict[str, list[dict[str, Any]]] = {}
    for obj in objects:
        result.setdefault(obj["kind"], []).append(obj)
    return result


_SYNC_RE = re.compile(r"\bsync\b")


def _is_sync(obj: dict[str, Any]) -> bool:
    """True if this object belongs to the sync infrastructure.

    Uses word-boundary matching so that the ``synctest`` workload
    (which contains "sync" as a substring) is not misidentified.
    """
    name = obj.get("name", "")
    ns = obj.get("namespace", "")
    return bool(_SYNC_RE.search(name) or _SYNC_RE.search(ns))


def _is_drop_cache(obj: dict[str, Any]) -> bool:
    name = obj.get("name", "")
    return name.endswith("-dc")


def _worker_objects(
    objects: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Non-sync, non-drop-cache workload objects."""
    return [
        o for o in objects
        if o["kind"] in _WORKER_KINDS
        and not _is_sync(o)
        and not _is_drop_cache(o)
    ]


def _workload_services(
    objects: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Services that are NOT sync-related."""
    return [
        o for o in objects
        if o["kind"] == "Service" and not _is_sync(o)
    ]


def _get_labels(obj: dict[str, Any]) -> dict[str, str]:
    """Return labels from the top-level or template metadata."""
    labels = obj.get("labels", {})
    if not labels:
        labels = obj.get("template_labels", {})
    return labels


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def _reset_workloads():
    """Re-snapshot workload singleton state to prevent cross-test leaks."""
    from clusterbuster.driver.workload_registry import all_workloads
    import clusterbuster.driver.workloads  # noqa: F401 — trigger registration

    saved: list[tuple[object, dict]] = []
    for wl in all_workloads():
        saved.append((wl, copy.deepcopy(wl.__dict__)))
    yield
    for wl, state in saved:
        wl.__dict__.clear()
        wl.__dict__.update(state)


# ---------------------------------------------------------------------------
# Build the test matrix
# ---------------------------------------------------------------------------

def _golden_cases() -> list[tuple[str, str]]:
    cases = []
    for wl in WORKLOADS:
        for dt in DEPLOYMENT_TYPES:
            path = GOLDEN_DIR / f"{wl}_{dt}.json"
            if path.exists():
                cases.append((wl, dt))
    return cases


_CASES = _golden_cases()


def _case_id(val: tuple[str, str]) -> str:
    return f"{val[0]}_{val[1]}"


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestGoldenObjectCounts:
    """Verify object counts match between Python and bash."""

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_namespace_count(self, workload, dep_type, capsys):
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)
        g_ns = [o for o in golden if o["kind"] == "Namespace"]
        p_ns = [o for o in py_objs if o["kind"] == "Namespace"]
        assert len(p_ns) == len(g_ns), (
            f"[{workload}/{dep_type}] Namespace count: "
            f"golden={len(g_ns)}, python={len(p_ns)}"
        )

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_namespace_names(self, workload, dep_type, capsys):
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)
        g_names = sorted(o["name"] for o in golden if o["kind"] == "Namespace")
        p_names = sorted(o["name"] for o in py_objs if o["kind"] == "Namespace")
        assert p_names == g_names

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_worker_object_count(self, workload, dep_type, capsys):
        """Same number of worker role objects (Pod/Deployment/RS/VM)."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)
        g_workers = _worker_objects(golden)
        p_workers = _worker_objects(py_objs)
        assert len(p_workers) == len(g_workers), (
            f"[{workload}/{dep_type}] Worker object count: "
            f"golden={len(g_workers)} ({[o['kind'] for o in g_workers]}), "
            f"python={len(p_workers)} ({[o['kind'] for o in p_workers]})"
        )

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_sync_pod_exists(self, workload, dep_type, capsys):
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)
        sync_pods = [
            o for o in py_objs
            if o["kind"] == "Pod" and _is_sync(o)
        ]
        assert len(sync_pods) >= 1, (
            f"[{workload}/{dep_type}] No sync pod found"
        )

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_sync_service_exists(self, workload, dep_type, capsys):
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)
        sync_svcs = [
            o for o in py_objs
            if o["kind"] == "Service" and _is_sync(o)
        ]
        assert len(sync_svcs) >= 1


class TestGoldenWorkerLabels:
    """Worker object labels match between Python and bash."""

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_worker_label_keys(self, workload, dep_type, capsys):
        """Worker objects must have the same label keys as the bash golden."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_workers = _worker_objects(golden)
        p_workers = _worker_objects(py_objs)

        if len(g_workers) != len(p_workers):
            pytest.skip("Worker count mismatch — covered by count test")

        # Sort by label count for stable pairing between bash/python
        g_workers.sort(key=lambda o: len(o.get("labels", {})))
        p_workers.sort(key=lambda o: len(o.get("labels", {})))

        for g_obj, p_obj in zip(g_workers, p_workers):
            g_labels = set(g_obj.get("labels", {}).keys())
            p_labels = set(p_obj.get("labels", {}).keys())
            missing = g_labels - p_labels
            assert not missing, (
                f"[{workload}/{dep_type}] "
                f"golden {g_obj['kind']} {g_obj['name']}: "
                f"missing label keys in Python: {sorted(missing)}"
            )

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_worker_objtype_label(self, workload, dep_type, capsys):
        """All worker objects must have objtype=worker."""
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)
        for obj in _worker_objects(py_objs):
            labels = _get_labels(obj)
            assert labels.get("clusterbuster-objtype") == "worker", (
                f"[{workload}/{dep_type}] {obj['kind']} {obj['name']}: "
                f"objtype={labels.get('clusterbuster-objtype')!r}"
            )

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_worker_boolean_labels(self, workload, dep_type, capsys):
        """Boolean and static label values must match the golden."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_workers = _worker_objects(golden)
        p_workers = _worker_objects(py_objs)
        if len(g_workers) != len(p_workers):
            pytest.skip("Worker count mismatch")

        g_workers.sort(key=lambda o: len(o.get("labels", {})))
        p_workers.sort(key=lambda o: len(o.get("labels", {})))

        static_keys = [
            "clusterbuster-objtype", "clusterbuster", "clusterbusterbase",
            "clusterbuster-workload", "clusterbuster-logger",
        ]

        for g_obj, p_obj in zip(g_workers, p_workers):
            g_labels = g_obj.get("labels", {})
            p_labels = p_obj.get("labels", {})
            for key in static_keys:
                if key in g_labels:
                    assert key in p_labels, (
                        f"[{workload}/{dep_type}] {g_obj['name']}: "
                        f"missing label {key}"
                    )
                    assert p_labels[key] == g_labels[key], (
                        f"[{workload}/{dep_type}] {g_obj['name']}: "
                        f"{key}: golden={g_labels[key]!r}, "
                        f"python={p_labels[key]!r}"
                    )

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_worker_uuid_label_patterns(self, workload, dep_type, capsys):
        """UUID-based labels must use the correct UUID/XUUID pattern."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_workers = _worker_objects(golden)
        p_workers = _worker_objects(py_objs)
        if len(g_workers) != len(p_workers):
            pytest.skip("Worker count mismatch")

        g_workers.sort(key=lambda o: len(o.get("labels", {})))
        p_workers.sort(key=lambda o: len(o.get("labels", {})))

        uuid_keys = [
            "clusterbuster-uuid", "clusterbuster-id",
            "clusterbuster-xuuid", "clusterbuster-worker",
            "clusterbuster-x-worker", "clusterbuster-monitor",
        ]
        for g_obj, p_obj in zip(g_workers, p_workers):
            g_labels = g_obj.get("labels", {})
            p_labels = p_obj.get("labels", {})
            for key in uuid_keys:
                if key not in g_labels:
                    continue
                assert key in p_labels, (
                    f"[{workload}/{dep_type}] {g_obj['name']}: "
                    f"missing UUID label {key}"
                )
                assert p_labels[key] == g_labels[key], (
                    f"[{workload}/{dep_type}] {g_obj['name']}: "
                    f"{key}: golden={g_labels[key]!r}, "
                    f"python={p_labels[key]!r}"
                )


class TestGoldenNamespaceLabels:
    """Verify namespace label keys match."""

    @pytest.mark.parametrize("workload,dep_type", _CASES, ids=[_case_id(c) for c in _CASES])
    def test_namespace_label_keys(self, workload, dep_type, capsys):
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_nss = sorted(
            (o for o in golden if o["kind"] == "Namespace"),
            key=lambda o: o["name"],
        )
        p_nss = sorted(
            (o for o in py_objs if o["kind"] == "Namespace"),
            key=lambda o: o["name"],
        )

        pod_sec = {"pod-security.kubernetes.io/enforce",
                   "pod-security.kubernetes.io/audit",
                   "pod-security.kubernetes.io/warn"}

        for g_ns, p_ns in zip(g_nss, p_nss):
            g_keys = set(g_ns.get("labels", {}).keys()) - pod_sec
            p_keys = set(p_ns.get("labels", {}).keys()) - pod_sec
            missing = g_keys - p_keys
            assert not missing, (
                f"[{workload}/{dep_type}] Namespace {g_ns['name']}: "
                f"missing label keys: {sorted(missing)}"
            )


class TestGoldenVMLabels:
    """VM-specific label verification."""

    _VM_CASES = [c for c in _CASES if c[1] == "vm"]

    @pytest.mark.parametrize(
        "workload,dep_type", _VM_CASES,
        ids=[_case_id(c) for c in _VM_CASES],
    )
    def test_vm_count(self, workload, dep_type, capsys):
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)
        g_vms = [o for o in golden if o["kind"] == "VirtualMachine"]
        p_vms = [o for o in py_objs if o["kind"] == "VirtualMachine"]
        assert len(p_vms) == len(g_vms), (
            f"[{workload}/vm] VM count: golden={len(g_vms)}, "
            f"python={len(p_vms)}"
        )

    @pytest.mark.parametrize(
        "workload,dep_type", _VM_CASES,
        ids=[_case_id(c) for c in _VM_CASES],
    )
    def test_vm_label_keys(self, workload, dep_type, capsys):
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_vms = sorted(
            (o for o in golden if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        p_vms = sorted(
            (o for o in py_objs if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        if len(g_vms) != len(p_vms):
            pytest.skip("VM count mismatch")

        for g_vm, p_vm in zip(g_vms, p_vms):
            g_keys = set(g_vm.get("labels", {}).keys())
            p_keys = set(p_vm.get("labels", {}).keys())
            missing = g_keys - p_keys
            assert not missing, (
                f"[{workload}/vm] VM {g_vm['name']}: "
                f"missing label keys: {sorted(missing)}"
            )

    @pytest.mark.parametrize(
        "workload,dep_type", _VM_CASES,
        ids=[_case_id(c) for c in _VM_CASES],
    )
    def test_vm_template_label_keys(self, workload, dep_type, capsys):
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_vms = sorted(
            (o for o in golden if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        p_vms = sorted(
            (o for o in py_objs if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        if len(g_vms) != len(p_vms):
            pytest.skip("VM count mismatch")

        for g_vm, p_vm in zip(g_vms, p_vms):
            g_keys = set(g_vm.get("template_labels", {}).keys())
            p_keys = set(p_vm.get("template_labels", {}).keys())
            missing = g_keys - p_keys
            assert not missing, (
                f"[{workload}/vm] VM {g_vm['name']}: "
                f"missing template label keys: {sorted(missing)}"
            )


class TestGoldenServicePorts:
    """Verify workload services have correct ports."""

    _SVC_CASES = [c for c in _CASES if c[0] in _CLIENT_SERVER]

    @pytest.mark.parametrize(
        "workload,dep_type", _SVC_CASES,
        ids=[_case_id(c) for c in _SVC_CASES],
    )
    def test_workload_service_port_numbers(self, workload, dep_type, capsys):
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_svcs = _workload_services(golden)
        p_svcs = _workload_services(py_objs)

        assert len(p_svcs) == len(g_svcs), (
            f"[{workload}/{dep_type}] Workload service count: "
            f"golden={len(g_svcs)}, python={len(p_svcs)}"
        )

        for g_svc in g_svcs:
            g_ports = g_svc.get("ports", [])
            if not g_ports:
                continue
            g_port_set = {(p["port"], p["protocol"]) for p in g_ports}

            matched = any(
                {(p["port"], p["protocol"]) for p in p_svc.get("ports", [])}
                == g_port_set
                for p_svc in p_svcs
                if p_svc.get("ports")
            )
            assert matched, (
                f"[{workload}/{dep_type}] No Python service matches "
                f"golden port set (first 6): "
                f"{sorted(g_port_set)[:6]}..."
            )

    @pytest.mark.parametrize(
        "workload,dep_type", _SVC_CASES,
        ids=[_case_id(c) for c in _SVC_CASES],
    )
    def test_workload_service_selector_key(self, workload, dep_type, capsys):
        """Workload service selector should use the 'replica' key."""
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        for svc in _workload_services(py_objs):
            selector = svc.get("selector", {})
            if selector:
                assert "replica" in selector, (
                    f"[{workload}/{dep_type}] Service {svc['name']}: "
                    f"selector should use 'replica' key, "
                    f"got {list(selector.keys())}"
                )


class TestGoldenDeploymentReplicaset:
    """Verify Deployment/ReplicaSet types produce correct structure."""

    _DEP_RS_CASES = [c for c in _CASES if c[1] in ("deployment", "replicaset")]

    @pytest.mark.parametrize(
        "workload,dep_type", _DEP_RS_CASES,
        ids=[_case_id(c) for c in _DEP_RS_CASES],
    )
    def test_contains_correct_kind(self, workload, dep_type, capsys):
        """Output should contain Deployment or ReplicaSet as appropriate."""
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        expected_kind = "Deployment" if dep_type == "deployment" else "ReplicaSet"
        matching = [o for o in py_objs if o["kind"] == expected_kind]
        assert len(matching) >= 1, (
            f"[{workload}/{dep_type}] No {expected_kind} found"
        )

    @pytest.mark.parametrize(
        "workload,dep_type", _DEP_RS_CASES,
        ids=[_case_id(c) for c in _DEP_RS_CASES],
    )
    def test_has_match_labels(self, workload, dep_type, capsys):
        """Deployment/ReplicaSet should have selector.matchLabels."""
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        expected_kind = "Deployment" if dep_type == "deployment" else "ReplicaSet"
        deps = [o for o in py_objs if o["kind"] == expected_kind]

        for dep in deps:
            assert dep.get("match_labels"), (
                f"[{workload}/{dep_type}] {expected_kind} {dep['name']}: "
                f"missing matchLabels"
            )

    @pytest.mark.parametrize(
        "workload,dep_type", _DEP_RS_CASES,
        ids=[_case_id(c) for c in _DEP_RS_CASES],
    )
    def test_has_template_labels(self, workload, dep_type, capsys):
        """Deployment/ReplicaSet template should have labels."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        expected_kind = "Deployment" if dep_type == "deployment" else "ReplicaSet"
        p_deps = [o for o in py_objs if o["kind"] == expected_kind]

        # Golden may have Pods instead (bash -p flag), so check
        # against golden Deployment/RS if available; otherwise
        # check against golden worker Pods for label keys.
        g_deps = [o for o in golden if o["kind"] == expected_kind]
        if g_deps:
            g_deps.sort(key=lambda o: o.get("name", ""))
            p_deps.sort(key=lambda o: o.get("name", ""))
            for g_dep, p_dep in zip(g_deps, p_deps):
                g_keys = set(g_dep.get("template_labels", {}).keys())
                p_keys = set(p_dep.get("template_labels", {}).keys())
                missing = g_keys - p_keys
                assert not missing, (
                    f"[{workload}/{dep_type}] template_labels "
                    f"missing keys: {sorted(missing)}"
                )
        else:
            g_workers = _worker_objects(golden)
            if g_workers:
                g_keys = set(g_workers[0].get("labels", {}).keys())
                for dep in p_deps:
                    p_keys = set(dep.get("template_labels", {}).keys())
                    missing = g_keys - p_keys
                    assert not missing, (
                        f"[{workload}/{dep_type}] template_labels "
                        f"missing keys vs golden Pod: {sorted(missing)}"
                    )

    @pytest.mark.parametrize(
        "workload,dep_type", _DEP_RS_CASES,
        ids=[_case_id(c) for c in _DEP_RS_CASES],
    )
    def test_template_labels_match_pod_labels(self, workload, dep_type, capsys):
        """Deployment/RS template labels should match what the pod
        deployment type produces for the same workload."""
        raw_pod = _python_dryrun(workload, "pod", capsys)
        pod_objs = _extract_python_objects(raw_pod)

        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        expected_kind = "Deployment" if dep_type == "deployment" else "ReplicaSet"
        p_deps = [o for o in py_objs if o["kind"] == expected_kind]
        pod_workers = _worker_objects(pod_objs)

        if not p_deps or not pod_workers:
            pytest.skip("No objects to compare")

        is_cs = workload in _CLIENT_SERVER
        if is_cs:
            pod_workers = [
                o for o in pod_workers
                if "client" in o.get("name", "")
            ]
            if not pod_workers:
                pytest.skip("No client pods to compare")

        pod_keys = set(pod_workers[0].get("labels", {}).keys())
        dep_keys = set(p_deps[0].get("template_labels", {}).keys())

        pod_keys.discard("replica")

        missing = pod_keys - dep_keys
        assert not missing, (
            f"[{workload}/{dep_type}] Template labels missing keys "
            f"that pod type has: {sorted(missing)}"
        )


class TestGoldenVMDomain:
    """VM domain structure: disk serials, volumes, and cloud-init boot commands."""

    _VM_CASES = [c for c in _CASES if c[1] == "vm"]

    @pytest.mark.parametrize(
        "workload,dep_type", _VM_CASES,
        ids=[_case_id(c) for c in _VM_CASES],
    )
    def test_vm_disk_serials(self, workload, dep_type, capsys):
        """Disk serial fields must match (critical for /dev/disk/by-id paths)."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_vms = sorted(
            (o for o in golden if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        p_vms = sorted(
            (o for o in py_objs if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        if len(g_vms) != len(p_vms):
            pytest.skip("VM count mismatch")

        for g_vm, p_vm in zip(g_vms, p_vms):
            g_serials = g_vm.get("vm_disk_serials", [])
            p_serials = p_vm.get("vm_disk_serials", [])
            assert p_serials == g_serials, (
                f"[{workload}/vm] VM {g_vm['name']}: "
                f"disk serials: golden={g_serials}, python={p_serials}"
            )

    @pytest.mark.parametrize(
        "workload,dep_type", _VM_CASES,
        ids=[_case_id(c) for c in _VM_CASES],
    )
    def test_vm_volume_types(self, workload, dep_type, capsys):
        """VM volume types must match bash."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_vms = sorted(
            (o for o in golden if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        p_vms = sorted(
            (o for o in py_objs if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        if len(g_vms) != len(p_vms):
            pytest.skip("VM count mismatch")

        for g_vm, p_vm in zip(g_vms, p_vms):
            g_types = g_vm.get("vm_volume_types", [])
            p_types = p_vm.get("vm_volume_types", [])
            assert p_types == g_types, (
                f"[{workload}/vm] VM {g_vm['name']}: "
                f"volume types: golden={g_types}, python={p_types}"
            )

    @pytest.mark.parametrize(
        "workload,dep_type", _VM_CASES,
        ids=[_case_id(c) for c in _VM_CASES],
    )
    def test_vm_bootcmd_structure(self, workload, dep_type, capsys):
        """Cloud-init bootcmd must have same structural commands (mkdir, mount, mkfs)."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_vms = sorted(
            (o for o in golden if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        p_vms = sorted(
            (o for o in py_objs if o["kind"] == "VirtualMachine"),
            key=lambda o: o.get("name", ""),
        )
        if len(g_vms) != len(p_vms):
            pytest.skip("VM count mismatch")

        for g_vm, p_vm in zip(g_vms, p_vms):
            g_cmds = g_vm.get("vm_bootcmd_structural", [])
            p_cmds = p_vm.get("vm_bootcmd_structural", [])
            assert p_cmds == g_cmds, (
                f"[{workload}/vm] VM {g_vm['name']}: "
                f"bootcmd structure: golden={g_cmds}, python={p_cmds}"
            )


class TestGoldenPodSpec:
    """Pod-level spec fields: restartPolicy, securityContext, affinity."""

    _POD_CASES = [c for c in _CASES if c[1] == "pod"]

    @pytest.mark.parametrize(
        "workload,dep_type", _POD_CASES,
        ids=[_case_id(c) for c in _POD_CASES],
    )
    def test_restart_policy(self, workload, dep_type, capsys):
        """Worker pods must have restartPolicy matching bash."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_workers = _worker_objects(golden)
        p_workers = _worker_objects(py_objs)

        for g_w in g_workers:
            g_rp = g_w.get("restart_policy")
            if not g_rp:
                continue
            matches = [p for p in p_workers
                       if p.get("name") == g_w.get("name")]
            for p_w in matches:
                p_rp = p_w.get("restart_policy")
                assert p_rp == g_rp, (
                    f"[{workload}/pod] {g_w['name']}: "
                    f"restartPolicy: golden={g_rp}, python={p_rp}"
                )

    @pytest.mark.parametrize(
        "workload,dep_type", _POD_CASES,
        ids=[_case_id(c) for c in _POD_CASES],
    )
    def test_run_as_non_root(self, workload, dep_type, capsys):
        """Restricted pods must have runAsNonRoot matching bash."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_workers = _worker_objects(golden)
        p_workers = _worker_objects(py_objs)

        for g_w in g_workers:
            if "run_as_non_root" not in g_w:
                continue
            matches = [p for p in p_workers
                       if p.get("name") == g_w.get("name")]
            for p_w in matches:
                assert p_w.get("run_as_non_root") == g_w["run_as_non_root"], (
                    f"[{workload}/pod] {g_w['name']}: "
                    f"runAsNonRoot: golden={g_w['run_as_non_root']}, "
                    f"python={p_w.get('run_as_non_root')}"
                )

    _SYSCTL_CASES = [
        c for c in _POD_CASES
        if c[0] in ("uperf", "server")
    ]

    @pytest.mark.parametrize(
        "workload,dep_type", _SYSCTL_CASES,
        ids=[_case_id(c) for c in _SYSCTL_CASES],
    )
    def test_container_sysctls(self, workload, dep_type, capsys):
        """Workloads with sysctls must include them in the container securityContext."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_workers = _worker_objects(golden)
        p_workers = _worker_objects(py_objs)

        for g_w in g_workers:
            g_sc = g_w.get("container_sysctls", [])
            if not g_sc:
                continue
            matches = [p for p in p_workers
                       if p.get("name") == g_w.get("name")]
            for p_w in matches:
                p_sc = p_w.get("container_sysctls", [])
                assert p_sc == g_sc, (
                    f"[{workload}/pod] {g_w['name']}: "
                    f"sysctls: golden={g_sc}, python={p_sc}"
                )

    _DC_CASES = [
        c for c in _POD_CASES
        if c[0] in ("fio", "files")
    ]

    @pytest.mark.parametrize(
        "workload,dep_type", _DC_CASES,
        ids=[_case_id(c) for c in _DC_CASES],
    )
    def test_drop_cache_affinity(self, workload, dep_type, capsys):
        """Drop-cache pods must have podAffinity matching bash."""
        golden = _load_golden(workload, dep_type)
        raw = _python_dryrun(workload, dep_type, capsys)
        py_objs = _extract_python_objects(raw)

        g_dc = [o for o in golden if "dc" in o.get("name", "")]
        p_dc = [o for o in py_objs if "dc" in o.get("name", "")]

        for g_pod in g_dc:
            assert g_pod.get("has_pod_affinity"), (
                f"Golden drop-cache pod {g_pod['name']} missing podAffinity"
            )
        for p_pod in p_dc:
            assert p_pod.get("has_pod_affinity"), (
                f"Python drop-cache pod {p_pod['name']} missing podAffinity"
            )


class TestMultiNamespace:
    """Verify that multi-namespace runs produce correct structure."""

    _NUM_NS = 3

    _SIMPLE_CASES = [
        ("cpusoaker", "pod"),
        ("cpusoaker", "replicaset"),
    ]

    _COMPLEX_CASES = [
        ("fio", "pod"),
        ("fio", "replicaset"),
        ("fio", "vm"),
        ("uperf", "pod"),
        ("uperf", "replicaset"),
        ("uperf", "vm"),
    ]

    _ALL_CASES = _SIMPLE_CASES + _COMPLEX_CASES

    @staticmethod
    def _multi_ns_dryrun(
        workload: str, dep_type: str, num_ns: int, capsys: Any,
    ) -> list[dict[str, Any]]:
        from clusterbuster.driver import run_from_argv
        args = [
            "-n",
            f"--uuid={FIXED_UUID}",
            f"--workload={workload}",
            f"--deployment-type={dep_type}",
            f"--namespaces={num_ns}",
        ]
        rc = run_from_argv(args)
        assert rc == 0, f"dry-run failed for {workload}/{dep_type}/ns={num_ns}"
        return _extract_python_objects(capsys.readouterr().out)

    # ------------------------------------------------------------------
    # Namespace creation
    # ------------------------------------------------------------------

    @pytest.mark.parametrize(
        "workload,dep_type", _ALL_CASES,
        ids=[f"{w}_{d}" for w, d in _ALL_CASES],
    )
    def test_namespace_count(self, workload, dep_type, capsys):
        """Correct number of namespaces: N workload + 1 sync."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        nss = [o for o in objs if o["kind"] == "Namespace"]
        assert len(nss) == self._NUM_NS + 1, (
            f"Expected {self._NUM_NS + 1} namespaces (sync + {self._NUM_NS} "
            f"workload), got {len(nss)}: "
            f"{[n['name'] for n in nss]}"
        )

    @pytest.mark.parametrize(
        "workload,dep_type", _ALL_CASES,
        ids=[f"{w}_{d}" for w, d in _ALL_CASES],
    )
    def test_namespace_names(self, workload, dep_type, capsys):
        """Namespace names follow the clusterbuster-<N> convention."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        ns_names = sorted(o["name"] for o in objs if o["kind"] == "Namespace")
        expected = sorted(
            [f"clusterbuster-{i}" for i in range(self._NUM_NS)]
            + ["clusterbuster-sync"]
        )
        assert ns_names == expected

    # ------------------------------------------------------------------
    # ExternalName services
    # ------------------------------------------------------------------

    @pytest.mark.parametrize(
        "workload,dep_type", _ALL_CASES,
        ids=[f"{w}_{d}" for w, d in _ALL_CASES],
    )
    def test_external_services_per_namespace(self, workload, dep_type, capsys):
        """Each namespace gets an ExternalName service for sync."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        ext_svcs = [
            o for o in objs
            if o.get("kind") == "Service"
            and o.get("service_type") == "ExternalName"
        ]
        assert len(ext_svcs) == self._NUM_NS, (
            f"Expected {self._NUM_NS} ExternalName services, "
            f"got {len(ext_svcs)}"
        )
        ext_namespaces = sorted(o["namespace"] for o in ext_svcs)
        expected_ns = sorted(f"clusterbuster-{i}" for i in range(self._NUM_NS))
        assert ext_namespaces == expected_ns

    @pytest.mark.parametrize(
        "workload,dep_type", _ALL_CASES,
        ids=[f"{w}_{d}" for w, d in _ALL_CASES],
    )
    def test_external_service_ports(self, workload, dep_type, capsys):
        """ExternalName services must carry both sync port numbers."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        ext_svcs = [
            o for o in objs
            if o.get("kind") == "Service"
            and o.get("service_type") == "ExternalName"
        ]
        for svc in ext_svcs:
            ports = svc.get("ports", [])
            assert len(ports) >= 2, (
                f"ExternalName in {svc['namespace']} has {len(ports)} "
                f"ports, expected >= 2"
            )
            port_nums = {p["port"] for p in ports}
            assert len(port_nums) >= 2, (
                f"ExternalName in {svc['namespace']} has "
                f"only {len(port_nums)} distinct port numbers"
            )

    # ------------------------------------------------------------------
    # Worker object distribution
    # ------------------------------------------------------------------

    @pytest.mark.parametrize(
        "workload,dep_type", _ALL_CASES,
        ids=[f"{w}_{d}" for w, d in _ALL_CASES],
    )
    def test_workers_in_workload_namespaces(self, workload, dep_type, capsys):
        """Worker objects should only be in workload namespaces, not sync."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        workers = _worker_objects(objs)
        assert len(workers) >= 1
        for w in workers:
            assert "sync" not in w.get("namespace", ""), (
                f"Worker {w['name']} unexpectedly in sync namespace"
            )

    @pytest.mark.parametrize(
        "workload,dep_type", _ALL_CASES,
        ids=[f"{w}_{d}" for w, d in _ALL_CASES],
    )
    def test_workers_spread_across_namespaces(self, workload, dep_type, capsys):
        """Workers should be distributed across all workload namespaces."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        workers = _worker_objects(objs)
        worker_nss = {w["namespace"] for w in workers}
        expected_nss = {f"clusterbuster-{i}" for i in range(self._NUM_NS)}
        assert worker_nss == expected_nss, (
            f"Workers present in {sorted(worker_nss)}, "
            f"expected {sorted(expected_nss)}"
        )

    # ------------------------------------------------------------------
    # Sync infrastructure stays in sync namespace
    # ------------------------------------------------------------------

    @pytest.mark.parametrize(
        "workload,dep_type", _ALL_CASES,
        ids=[f"{w}_{d}" for w, d in _ALL_CASES],
    )
    def test_sync_pod_in_sync_namespace(self, workload, dep_type, capsys):
        """The sync pod must be in the sync namespace."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        sync_pods = [
            o for o in objs
            if o["kind"] == "Pod" and _is_sync(o)
        ]
        assert len(sync_pods) >= 1
        for sp in sync_pods:
            assert "sync" in sp["namespace"], (
                f"Sync pod {sp['name']} in {sp['namespace']}, "
                f"expected sync namespace"
            )

    # ------------------------------------------------------------------
    # ConfigMaps and Secrets per namespace
    # ------------------------------------------------------------------

    @pytest.mark.parametrize(
        "workload,dep_type", _ALL_CASES,
        ids=[f"{w}_{d}" for w, d in _ALL_CASES],
    )
    def test_configmaps_per_namespace(self, workload, dep_type, capsys):
        """Each workload namespace must have at least one ConfigMap."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        cms = [o for o in objs if o["kind"] == "ConfigMap"]
        cm_nss = {o["namespace"] for o in cms}
        expected_nss = {f"clusterbuster-{i}" for i in range(self._NUM_NS)}
        assert expected_nss <= cm_nss, (
            f"ConfigMaps missing from namespaces: "
            f"{sorted(expected_nss - cm_nss)}"
        )

    # ------------------------------------------------------------------
    # PSA labels on namespaces
    # ------------------------------------------------------------------

    @pytest.mark.parametrize(
        "workload,dep_type", _ALL_CASES,
        ids=[f"{w}_{d}" for w, d in _ALL_CASES],
    )
    def test_namespace_psa_labels(self, workload, dep_type, capsys):
        """All namespaces should carry pod-security.kubernetes.io labels."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        nss = [o for o in objs if o["kind"] == "Namespace"]
        psa_prefix = "pod-security.kubernetes.io/"
        for ns in nss:
            labels = ns.get("labels", {})
            psa_keys = [k for k in labels if k.startswith(psa_prefix)]
            assert len(psa_keys) >= 1, (
                f"Namespace {ns['name']} has no PSA labels"
            )

    # ------------------------------------------------------------------
    # Client-server workloads: server services per namespace
    # ------------------------------------------------------------------

    _CS_CASES = [c for c in _COMPLEX_CASES if c[0] == "uperf"]

    @pytest.mark.parametrize(
        "workload,dep_type", _CS_CASES,
        ids=[f"{w}_{d}" for w, d in _CS_CASES],
    )
    def test_uperf_server_services(self, workload, dep_type, capsys):
        """uperf should create a headless service per workload namespace."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        workload_svcs = _workload_services(objs)
        assert len(workload_svcs) >= self._NUM_NS, (
            f"Expected >= {self._NUM_NS} workload services for uperf, "
            f"got {len(workload_svcs)}"
        )
        svc_nss = {s["namespace"] for s in workload_svcs}
        expected_nss = {f"clusterbuster-{i}" for i in range(self._NUM_NS)}
        assert expected_nss <= svc_nss, (
            f"Workload services missing from: {sorted(expected_nss - svc_nss)}"
        )

    # ------------------------------------------------------------------
    # FIO-specific: drop-cache pods per namespace
    # ------------------------------------------------------------------

    _FIO_CASES = [c for c in _COMPLEX_CASES if c[0] == "fio"]

    @pytest.mark.parametrize(
        "workload,dep_type", _FIO_CASES,
        ids=[f"{w}_{d}" for w, d in _FIO_CASES],
    )
    def test_fio_drop_cache_pods(self, workload, dep_type, capsys):
        """FIO multi-namespace should have drop-cache pods in each workload namespace."""
        objs = self._multi_ns_dryrun(workload, dep_type, self._NUM_NS, capsys)
        dc_pods = [o for o in objs if _is_drop_cache(o)]
        if not dc_pods:
            pytest.skip("No drop-cache pods generated (drop_cache may be off)")
        dc_nss = {o["namespace"] for o in dc_pods}
        expected_nss = {f"clusterbuster-{i}" for i in range(self._NUM_NS)}
        assert dc_nss == expected_nss, (
            f"Drop-cache pods in {sorted(dc_nss)}, "
            f"expected {sorted(expected_nss)}"
        )
